import pika
import json
import logging
from datetime import datetime
from uuid import UUID
from typing import Dict, Any
from config import settings

logger = logging.getLogger(__name__)


class RabbitMQPublisher:
    """RabbitMQ event publisher"""
    
    def __init__(self):
        self.connection = None
        self.channel = None
        self.exchange_name = 'micromail-events'
    
    def connect(self):
        """Connect to RabbitMQ"""
        try:
            self.connection = pika.BlockingConnection(
                pika.URLParameters(settings.RABBITMQ_URL)
            )
            self.channel = self.connection.channel()
            
            # Declare exchange
            self.channel.exchange_declare(
                exchange=self.exchange_name,
                exchange_type='topic',
                durable=True
            )
            logger.info("Connected to RabbitMQ")
        except Exception as e:
            logger.error(f"Failed to connect to RabbitMQ: {str(e)}")
            raise
    
    def publish_event(self, event_type: str, user_id: str, data: Dict[str, Any]):
        """Publish event to RabbitMQ"""
        try:
            if not self.channel:
                self.connect()
            
            event = {
                'event_type': event_type,
                'event_id': str(UUID(int=0)),  # Will be generated by service
                'timestamp': datetime.utcnow().isoformat(),
                'user_id': str(user_id),
                'data': data
            }
            
            message = json.dumps(event, default=str)
            
            # Determine routing key from event type
            routing_key = event_type  # e.g., "email.send", "draft.created"
            
            self.channel.basic_publish(
                exchange=self.exchange_name,
                routing_key=routing_key,
                body=message,
                properties=pika.BasicProperties(
                    content_type='application/json',
                    delivery_mode=pika.spec.PERSISTENT_DELIVERY_MODE
                )
            )
            logger.info(f"Published event: {event_type} for user: {user_id}")
        except Exception as e:
            logger.error(f"Failed to publish event: {str(e)}")
            raise
    
    def close(self):
        """Close RabbitMQ connection"""
        if self.connection:
            self.connection.close()
            logger.info("Closed RabbitMQ connection")


class RabbitMQConsumer:
    """RabbitMQ event consumer (for future use)"""
    
    def __init__(self, queue_name: str, routing_key: str):
        self.connection = None
        self.channel = None
        self.queue_name = queue_name
        self.routing_key = routing_key
        self.exchange_name = 'micromail-events'
    
    def connect(self):
        """Connect to RabbitMQ"""
        try:
            self.connection = pika.BlockingConnection(
                pika.URLParameters(settings.RABBITMQ_URL)
            )
            self.channel = self.connection.channel()
            
            # Declare exchange
            self.channel.exchange_declare(
                exchange=self.exchange_name,
                exchange_type='topic',
                durable=True
            )
            
            # Declare queue
            self.channel.queue_declare(queue=self.queue_name, durable=True)
            
            # Bind queue to exchange
            self.channel.queue_bind(
                exchange=self.exchange_name,
                queue=self.queue_name,
                routing_key=self.routing_key
            )
            logger.info(f"Connected to RabbitMQ - Queue: {self.queue_name}")
        except Exception as e:
            logger.error(f"Failed to connect to RabbitMQ: {str(e)}")
            raise
    
    def start_consuming(self, callback):
        """Start consuming events"""
        try:
            self.channel.basic_consume(
                queue=self.queue_name,
                on_message_callback=callback,
                auto_ack=False
            )
            logger.info(f"Starting to consume from queue: {self.queue_name}")
            self.channel.start_consuming()
        except Exception as e:
            logger.error(f"Error consuming events: {str(e)}")
            raise
    
    def close(self):
        """Close RabbitMQ connection"""
        if self.channel:
            self.channel.stop_consuming()
        if self.connection:
            self.connection.close()
            logger.info("Closed RabbitMQ connection")


# Global publisher instance
publisher = None


def get_publisher():
    """Get or create RabbitMQ publisher"""
    global publisher
    if publisher is None:
        publisher = RabbitMQPublisher()
        publisher.connect()
    return publisher
